import type { LanguageCode } from '@/i18n';

export interface ShareCopy {
  headline: string;
  tagline: string;
  traits: [string, string, string];
  warning: string;
  advice: string;
  quote: string;
}

export const SHARE_COPY: Record<LanguageCode, Record<string, ShareCopy>> = {
  'zh-CN': {
    BAYES: {
      headline: '先验炼金术士',
      tagline: '新数据一来，你先问它到底该把信念挪动几毫米。',
      traits: ['把误差棒当情绪管理', '开会时会说“后验上看”', '不轻易被一个 p 值带走'],
      warning: '容易把一个简单决定熬成小型贝叶斯研讨会。',
      advice: '在更新信念之前，先写下今天必须拍板的那件事。',
      quote: '我不是犹豫，我是在校准。',
    },
    PIPET: {
      headline: '移液枪战士',
      tagline: '同一排孔板，你能做出同一种安静的秩序。',
      traits: ['枪头盒永远补满', '标签贴得像出版物', '0.5 微升也有尊严'],
      warning: '可能为了手感一致，把午饭都推迟到下一轮离心后。',
      advice: '把关键手法写进协议，别让它只住在你的手腕里。',
      quote: '误差小，是因为手没飘。',
    },
    R2D2: {
      headline: '审稿人二号转世',
      tagline: '别人看见亮点，你已经在找那个缺失的对照。',
      traits: ['漂亮图先过怀疑关', '补充实验预判大师', '“样本量呢”说得很自然'],
      warning: '容易把项目保护到谁也发不出去。',
      advice: '先说哪个漏洞会改结论，再说哪个只是让你不舒服。',
      quote: '我不是挑刺，我是在帮它活过投稿。',
    },
    FIG1: {
      headline: '机制图建筑师',
      tagline: '白板一擦，你已经把混乱画成了 Figure 1。',
      traits: ['箭头有方向感', '通路图越画越清醒', '图例比摘要先成形'],
      warning: '偶尔会让虚线承担过多科研责任。',
      advice: '每画一条箭头，就给它配一条真正的证据。',
      quote: '先把机制画出来，再逼数据说实话。',
    },
    NULL: {
      headline: '阴性结果守门人',
      tagline: '你不怕没效应，只怕没效应也没人愿意诚实写。',
      traits: ['抽屉文件夹克星', '对“趋势”保持冷静', '能把零结果讲清楚'],
      warning: '可能把一点真实信号也先按进冷静水里。',
      advice: '把阴性结果写成边界条件，而不是一声叹气。',
      quote: '什么都没发生，也是一条结果。',
    },
    GIT: {
      headline: '版本控制圣骑士',
      tagline: '你相信一个好项目，应该能从提交记录里复活。',
      traits: ['commit message 有主谓宾', 'final 文件名会让你紧张', '分支合并前先深呼吸'],
      warning: '可能给两张图的小项目建出航天级流程。',
      advice: '把流程服务于结果，别让结果排队等流程长大。',
      quote: '在我机器上可以，不算复现。',
    },
    EXCEL: {
      headline: '表格巫师',
      tagline: '别人还在配环境，你已经用一张表救了组会。',
      traits: ['透视表临场救火', '颜色条件格式很会说话', '单元格里藏着半篇方法'],
      warning: '最危险的基础设施，往往叫做“随手算一下.xlsx”。',
      advice: '承重的表格，至少要有备份、版本和一次独立检查。',
      quote: '别小看网格，网格能顶住今晚。',
    },
    OMNI: {
      headline: '什么都想问的探索者',
      tagline: '主线结果刚稳定，你已经开始给异常点建新文件夹。',
      traits: ['读文献像开支线', '跨领域联想过快', '“顺便看看”很危险'],
      warning: '容易把一个项目繁殖成五个项目和十二个标签页。',
      advice: '每开一个新问题，就关掉一个旧问题或交给别人。',
      quote: '我知道这不是主线，但它在发光。',
    },
    NIGHT: {
      headline: '细胞守夜人',
      tagline: '白天像低表达，凌晨两点突然全基因组激活。',
      traits: ['截止日期前发光', '夜里改图效率惊人', '咖啡杯像培养瓶'],
      warning: '容易把短期爆发误认成可持续方案。',
      advice: '给明天的自己留一条能看懂的实验记录。',
      quote: '深夜不是办法，但今晚确实有用。',
    },
    REPRO: {
      headline: '重复性警察',
      tagline: '只要结果跑不回来，你就不承认它出过门。',
      traits: ['随机种子写得清楚', '环境文件随手就有', '截图不能当证据'],
      warning: '可能复现到全组都忘了最初的问题是什么。',
      advice: '先复现关键结论，再决定哪些细枝末节值得追到底。',
      quote: '能重跑，才算真的发生过。',
    },
    TODO: {
      headline: '永远补实验者',
      tagline: '每次快收尾，你都能想出一个合理的新对照。',
      traits: ['补实验理由很充分', '“最后一次”常有续集', '样本盒永远不空'],
      warning: '容易把 90% 完成度维护成长期生态位。',
      advice: '今天就写下“不再新增”的条件，并让一个同事保管它。',
      quote: '再补一个，就真的更稳了。',
    },
    ESC: {
      headline: '战略转向大师',
      tagline: '你不是逃跑，你是在数据把门焊死前换门。',
      traits: ['沉没成本免疫', '坏结果里找出口', '路线图会自己拐弯'],
      warning: '可能在真正突破前五分钟又换了方向。',
      advice: '转向前写清楚：是证据不行，还是你不耐烦了。',
      quote: '失败不是终点，是路线更新。',
    },
    MODEL: {
      headline: '模型宇宙建造师',
      tagline: '你看见一个现象，手已经伸向参数表。',
      traits: ['方程安抚焦虑', '模拟先于争论', '假设写得很认真'],
      warning: '容易让漂亮模型替现实把话说完。',
      advice: '让模型尽早碰一次脏数据，别只在白板上胜利。',
      quote: '如果能模拟，就先让它跑起来。',
    },
    GRANT: {
      headline: '经费召唤师',
      tagline: '你能把一个野心，翻译成评审愿意资助的段落。',
      traits: ['预算表也有叙事', 'impact 写得不脸红', 'deadline 前异常镇定'],
      warning: '容易把还没落地的结果讲得已经有楼层平面图。',
      advice: '每个宏大目标旁边，放一个本季度真能完成的实验。',
      quote: '愿景要大，耗材也要买得到。',
    },
    PREPRINT: {
      headline: '预印本冲锋手',
      tagline: '先把 v1 发出去，世界才有机会告诉你 v2 哪里不对。',
      traits: ['半成品也能先见人', 'Reviewer 还没来先改了', 'final_v7 只是过程'],
      warning: '容易把公开反馈当成项目管理工具。',
      advice: '发 v1 前，至少确认对照组、作者顺序和 source data 都真的存在。',
      quote: '先发出去，但别假装它已经完美。',
    },
    SOLO: {
      headline: '科研孤狼',
      tagline: '给你一扇门和一段安静时间，你能把难题拆完。',
      traits: ['独处时效率上线', '不爱边做边汇报', '深工作不是口号'],
      warning: '容易优秀到没人知道你正在优秀。',
      advice: '每周留一次小型同步，不必精彩，但要可见。',
      quote: '我不是失联，我是在算。',
    },
    CONTROL: {
      headline: '对照组守门员',
      tagline: '你最常问的不是结果多漂亮，而是“和谁比”。',
      traits: ['基线意识过强', '混杂因素雷达', '空白孔也有姓名'],
      warning: '可能把探索性实验设计成登月任务。',
      advice: '守住会改变解释的对照，放过只会增加重量的对照。',
      quote: '没有基线的显著性，我不太放心。',
    },
    PIPELINE: {
      headline: '工作流驯兽师',
      tagline: '只要同一件事手动做第三次，你就想写个脚本。',
      traits: ['文件夹会自己排队', '参数不靠口口相传', '日志比记忆可靠'],
      warning: '容易把一次性任务养成一只工具项目。',
      advice: '先确认流程会再用三次，再给它建仪表盘。',
      quote: '重复劳动出现两次，第三次就该自动化。',
    },
    PI: {
      headline: '导师化进行时',
      tagline: '你嘴上说只是问问，日程表已经长成了小型课题组。',
      traits: ['会议里看全局', '会自然追问论文进度', '别人项目也装在脑子里'],
      warning: '容易离数据越来越远，却离所有人的截止日期越来越近。',
      advice: '保留一个你亲手碰数据或样本的小项目。',
      quote: '我只是提醒一下，不催。',
    },
    GHOST: {
      headline: '组会隐身者',
      tagline: '你的麦克风很安静，但文档里突然多了关键答案。',
      traits: ['摄像头边界明确', '会后提交高质量文字', '会议越短越清醒'],
      warning: '容易把必要讨论也当作环境噪声过滤掉。',
      advice: '真正做决定的那十分钟，请出现一次。',
      quote: '我在，只是不在麦上。',
    },
    POLISH: {
      headline: '呈现优先完美主义者',
      tagline: '图还没完全证明结论，但你已经知道它该用什么字体。',
      traits: ['Figure legend 很会呼吸', '配色能救场', '排版前先叹气'],
      warning: '容易让漂亮图替还没检查完的数据争取信任。',
      advice: '先确认结论站得住，再让它穿上好看的外套。',
      quote: '不漂亮可以改，不真实不行。',
    },
  },
  'zh-TW': {
    BAYES: {
      headline: '先驗鍊金術士',
      tagline: '新資料一來，你先問它到底該把信念挪動幾毫米。',
      traits: ['把誤差棒當情緒管理', '開會時會說「後驗上看」', '不輕易被一個 p 值帶走'],
      warning: '容易把一個簡單決定熬成小型貝葉斯研討會。',
      advice: '在更新信念之前，先寫下今天必須拍板的那件事。',
      quote: '我不是猶豫，我是在校準。',
    },
    PIPET: {
      headline: '移液槍戰士',
      tagline: '同一排孔板，你能做出同一種安靜的秩序。',
      traits: ['槍頭盒永遠補滿', '標籤貼得像出版物', '0.5 微升也有尊嚴'],
      warning: '可能為了手感一致，把午飯都推遲到下一輪離心後。',
      advice: '把關鍵手法寫進協議，別讓它只住在你的手腕裡。',
      quote: '誤差小，是因為手沒飄。',
    },
    R2D2: {
      headline: '審稿人二號轉世',
      tagline: '別人看見亮點，你已經在找那個缺失的對照。',
      traits: ['漂亮圖先過懷疑關', '補充實驗預判大師', '「樣本量呢」說得很自然'],
      warning: '容易把專案保護到誰也發不出去。',
      advice: '先說哪個漏洞會改結論，再說哪個只是讓你不舒服。',
      quote: '我不是挑刺，我是在幫它活過投稿。',
    },
    FIG1: {
      headline: '機制圖建築師',
      tagline: '白板一擦，你已經把混亂畫成了 Figure 1。',
      traits: ['箭頭有方向感', '通路圖越畫越清醒', '圖例比摘要先成形'],
      warning: '偶爾會讓虛線承擔過多科研責任。',
      advice: '每畫一條箭頭，就給它配一條真正的證據。',
      quote: '先把機制畫出來，再逼資料說實話。',
    },
    NULL: {
      headline: '陰性結果守門人',
      tagline: '你不怕沒效應，只怕沒效應也沒人願意誠實寫。',
      traits: ['抽屜文件夾剋星', '對「趨勢」保持冷靜', '能把零結果講清楚'],
      warning: '可能把一點真實訊號也先按進冷靜水裡。',
      advice: '把陰性結果寫成邊界條件，而不是一聲嘆氣。',
      quote: '什麼都沒發生，也是一條結果。',
    },
    GIT: {
      headline: '版本控制聖騎士',
      tagline: '你相信一個好專案，應該能從提交紀錄裡復活。',
      traits: ['commit message 有主謂賓', 'final 檔名會讓你緊張', '分支合併前先深呼吸'],
      warning: '可能給兩張圖的小專案建出航太級流程。',
      advice: '把流程服務於結果，別讓結果排隊等流程長大。',
      quote: '在我機器上可以，不算重現。',
    },
    EXCEL: {
      headline: '表格巫師',
      tagline: '別人還在配環境，你已經用一張表救了組會。',
      traits: ['樞紐分析表臨場救火', '顏色條件格式很會說話', '儲存格裡藏著半篇方法'],
      warning: '最危險的基礎設施，往往叫做「隨手算一下.xlsx」。',
      advice: '承重的表格，至少要有備份、版本和一次獨立檢查。',
      quote: '別小看網格，網格能頂住今晚。',
    },
    OMNI: {
      headline: '什麼都想問的探索者',
      tagline: '主線結果剛穩定，你已經開始給異常點建新資料夾。',
      traits: ['讀文獻像開支線', '跨領域聯想過快', '「順便看看」很危險'],
      warning: '容易把一個專案繁殖成五個專案和十二個分頁。',
      advice: '每開一個新問題，就關掉一個舊問題或交給別人。',
      quote: '我知道這不是主線，但它在發光。',
    },
    NIGHT: {
      headline: '細胞守夜人',
      tagline: '白天像低表達，凌晨兩點突然全基因組啟動。',
      traits: ['截止日期前發光', '夜裡改圖效率驚人', '咖啡杯像培養瓶'],
      warning: '容易把短期爆發誤認成可持續方案。',
      advice: '給明天的自己留一條能看懂的實驗紀錄。',
      quote: '深夜不是辦法，但今晚確實有用。',
    },
    REPRO: {
      headline: '重現性警察',
      tagline: '只要結果跑不回來，你就不承認它出過門。',
      traits: ['隨機種子寫得清楚', '環境檔案隨手就有', '截圖不能當證據'],
      warning: '可能重現到全組都忘了最初的問題是什麼。',
      advice: '先重現關鍵結論，再決定哪些細枝末節值得追到底。',
      quote: '能重跑，才算真的發生過。',
    },
    TODO: {
      headline: '永遠補實驗者',
      tagline: '每次快收尾，你都能想出一個合理的新對照。',
      traits: ['補實驗理由很充分', '「最後一次」常有續集', '樣本盒永遠不空'],
      warning: '容易把 90% 完成度維護成長期生態位。',
      advice: '今天就寫下「不再新增」的條件，並讓一個同事保管它。',
      quote: '再補一個，就真的更穩了。',
    },
    ESC: {
      headline: '戰略轉向大師',
      tagline: '你不是逃跑，你是在資料把門焊死前換門。',
      traits: ['沉沒成本免疫', '壞結果裡找出口', '路線圖會自己轉彎'],
      warning: '可能在真正突破前五分鐘又換了方向。',
      advice: '轉向前寫清楚：是證據不行，還是你不耐煩了。',
      quote: '失敗不是終點，是路線更新。',
    },
    MODEL: {
      headline: '模型宇宙建造師',
      tagline: '你看見一個現象，手已經伸向參數表。',
      traits: ['方程安撫焦慮', '模擬先於爭論', '假設寫得很認真'],
      warning: '容易讓漂亮模型替現實把話說完。',
      advice: '讓模型盡早碰一次髒資料，別只在白板上勝利。',
      quote: '如果能模擬，就先讓它跑起來。',
    },
    GRANT: {
      headline: '經費召喚師',
      tagline: '你能把一個野心，翻譯成評審願意資助的段落。',
      traits: ['預算表也有敘事', 'impact 寫得不臉紅', 'deadline 前異常鎮定'],
      warning: '容易把還沒落地的結果講得已經有樓層平面圖。',
      advice: '每個宏大目標旁邊，放一個本季真能完成的實驗。',
      quote: '願景要大，耗材也要買得到。',
    },
    PREPRINT: {
      headline: '預印本衝鋒手',
      tagline: '先把 v1 發出去，世界才有機會告訴你 v2 哪裡不對。',
      traits: ['半成品也能先見人', 'Reviewer 還沒來先改了', 'final_v7 只是過程'],
      warning: '容易把公開回饋當成專案管理工具。',
      advice: '發 v1 前，至少確認對照組、作者順序和 source data 都真的存在。',
      quote: '先發出去，但別假裝它已經完美。',
    },
    SOLO: {
      headline: '科研孤狼',
      tagline: '給你一扇門和一段安靜時間，你能把難題拆完。',
      traits: ['獨處時效率上線', '不愛邊做邊回報', '深工作不是口號'],
      warning: '容易優秀到沒人知道你正在優秀。',
      advice: '每週留一次小型同步，不必精彩，但要可見。',
      quote: '我不是失聯，我是在算。',
    },
    CONTROL: {
      headline: '對照組守門員',
      tagline: '你最常問的不是結果多漂亮，而是「和誰比」。',
      traits: ['基線意識過強', '混雜因素雷達', '空白孔也有姓名'],
      warning: '可能把探索性實驗設計成登月任務。',
      advice: '守住會改變解釋的對照，放過只會增加重量的對照。',
      quote: '沒有基線的顯著性，我不太放心。',
    },
    PIPELINE: {
      headline: '工作流馴獸師',
      tagline: '只要同一件事手動做第三次，你就想寫個腳本。',
      traits: ['資料夾會自己排隊', '參數不靠口口相傳', '日誌比記憶可靠'],
      warning: '容易把一次性任務養成一隻工具專案。',
      advice: '先確認流程會再用三次，再給它建儀表板。',
      quote: '重複勞動出現兩次，第三次就該自動化。',
    },
    PI: {
      headline: '導師化進行時',
      tagline: '你嘴上說只是問問，行事曆已經長成了小型課題組。',
      traits: ['會議裡看全局', '會自然追問論文進度', '別人專案也裝在腦子裡'],
      warning: '容易離資料越來越遠，卻離所有人的截止日期越來越近。',
      advice: '保留一個你親手碰資料或樣本的小專案。',
      quote: '我只是提醒一下，不催。',
    },
    GHOST: {
      headline: '組會隱身者',
      tagline: '你的麥克風很安靜，但文件裡突然多了關鍵答案。',
      traits: ['鏡頭邊界明確', '會後提交高品質文字', '會議越短越清醒'],
      warning: '容易把必要討論也當作環境噪音過濾掉。',
      advice: '真正做決定的那十分鐘，請出現一次。',
      quote: '我在，只是不在麥上。',
    },
    POLISH: {
      headline: '呈現優先完美主義者',
      tagline: '圖還沒完全證明結論，但你已經知道它該用什麼字體。',
      traits: ['Figure legend 很會呼吸', '配色能救場', '排版前先嘆氣'],
      warning: '容易讓漂亮圖替還沒檢查完的資料爭取信任。',
      advice: '先確認結論站得住，再讓它穿上好看的外套。',
      quote: '不漂亮可以改，不真實不行。',
    },
  },
  en: {
    BAYES: {
      headline: 'Prior Alchemist',
      tagline: 'New data arrives; you ask how many millimetres belief should move.',
      traits: ['Error bars calm you down', 'Says “posteriorly speaking”', 'Not kidnapped by one p-value'],
      warning: 'Can turn a simple call into a tiny Bayesian seminar.',
      advice: 'Before updating belief, write down the decision due today.',
      quote: 'I am not hesitating. I am calibrating.',
    },
    PIPET: {
      headline: 'Precision Operator',
      tagline: 'Give you one plate, and every well learns manners.',
      traits: ['Tip boxes stay full', 'Labels look publishable', '0.5 uL deserves respect'],
      warning: 'May postpone lunch for the sake of identical hand feel.',
      advice: 'Put the critical touch into the protocol, not only your wrist.',
      quote: 'Small error bars start with steady hands.',
    },
    R2D2: {
      headline: 'Reviewer Two Reincarnated',
      tagline: 'Everyone sees the highlight; you see the missing control.',
      traits: ['Pretty figures must earn trust', 'Predicts supplement requests', 'Says “sample size?” naturally'],
      warning: 'Can protect a project until nobody can publish it.',
      advice: 'Separate flaws that change the conclusion from flaws that annoy you.',
      quote: 'I am not nitpicking. I am helping it survive submission.',
    },
    FIG1: {
      headline: 'Diagram Architect',
      tagline: 'The board gets wiped, and chaos has become Figure 1.',
      traits: ['Arrows know where to go', 'Pathways sharpen your thinking', 'Legends form before abstracts'],
      warning: 'Sometimes asks a dashed line to carry too much science.',
      advice: 'For every arrow, attach the evidence that earns it.',
      quote: 'Draw the mechanism, then make the data answer.',
    },
    NULL: {
      headline: 'Null Result Guardian',
      tagline: 'You do not fear no effect; you fear no one writing it honestly.',
      traits: ['Drawer-file enemy', 'Calm around “trends”', 'Explains zero cleanly'],
      warning: 'Can cool down a real signal before it has spoken.',
      advice: 'Frame the null as a boundary condition, not a sigh.',
      quote: 'Nothing happened. That is still a result.',
    },
    GIT: {
      headline: 'Version-Control Paladin',
      tagline: 'A good project should be resurrectable from its commits.',
      traits: ['Commit messages have grammar', 'final files cause stress', 'Breathes before merge conflicts'],
      warning: 'May build aerospace workflow for a two-figure project.',
      advice: 'Let workflow serve the result, not keep it waiting.',
      quote: 'Works on my machine is not reproducibility.',
    },
    EXCEL: {
      headline: 'Spreadsheet Sorcerer',
      tagline: 'While others set up environments, you save lab meeting with a sheet.',
      traits: ['Pivot tables fight fires', 'Conditional colour speaks', 'Methods hide in cells'],
      warning: 'The scariest infrastructure is often “quick_calc.xlsx”.',
      advice: 'If the sheet bears weight, give it backup, versions and a second check.',
      quote: 'Never underestimate a grid at 11 p.m.',
    },
    OMNI: {
      headline: 'Ask-Everything Explorer',
      tagline: 'The main result stabilises; you open a folder for the outlier.',
      traits: ['Reads papers as side quests', 'Cross-field leaps arrive fast', '“Quick look” is dangerous'],
      warning: 'Can breed one project into five projects and twelve tabs.',
      advice: 'For every new question, close an old one or hand it off.',
      quote: 'I know it is not the main story, but it is glowing.',
    },
    NIGHT: {
      headline: 'Deadline Nocturnalist',
      tagline: 'Low expression by day; whole-genome activation at 2 a.m.',
      traits: ['Glows near deadlines', 'Edits figures at night speed', 'Coffee cup as culture flask'],
      warning: 'Can mistake a short sprint for a sustainable system.',
      advice: 'Leave tomorrow-you a lab note that still makes sense.',
      quote: 'Night is not a method, but tonight it works.',
    },
    REPRO: {
      headline: 'Reproducibility Inspector',
      tagline: 'If the result will not come back, it never really left.',
      traits: ['Seeds are written down', 'Environment files appear', 'Screenshots are not evidence'],
      warning: 'Can reproduce until the room forgets the original question.',
      advice: 'Re-run the claim first; chase fine details second.',
      quote: 'If it re-runs, it happened.',
    },
    TODO: {
      headline: 'Eternal Experiment Extender',
      tagline: 'Every near-finish reveals one more reasonable control.',
      traits: ['Extra experiments sound fair', '“Final one” has sequels', 'Sample boxes never empty'],
      warning: 'Can maintain 90% completion as a permanent habitat.',
      advice: 'Write the no-new-work condition today and give it to a colleague.',
      quote: 'One more control and it really will be sturdier.',
    },
    ESC: {
      headline: 'Strategic Pivot Specialist',
      tagline: 'You are not fleeing; you are changing doors before data welds one shut.',
      traits: ['Immune to sunk cost', 'Finds exits in bad results', 'Roadmaps turn corners'],
      warning: 'May pivot five minutes before the breakthrough.',
      advice: 'Before pivoting, name whether evidence failed or patience did.',
      quote: 'Failure is not the end; it is a route update.',
    },
    MODEL: {
      headline: 'Model-Universe Builder',
      tagline: 'You see a phenomenon and reach for the parameter table.',
      traits: ['Equations soothe anxiety', 'Simulation before argument', 'Assumptions written carefully'],
      warning: 'Can let a beautiful model finish reality’s sentence.',
      advice: 'Make the model meet dirty data early, not only a whiteboard.',
      quote: 'If it can be simulated, let it run.',
    },
    GRANT: {
      headline: 'Funding Summoner',
      tagline: 'You translate ambition into paragraphs reviewers can fund.',
      traits: ['Budgets have narrative', 'Writes impact without flinching', 'Calm near deadlines'],
      warning: 'Can describe an unbuilt result like it has floor plans.',
      advice: 'Beside every grand aim, place one experiment doable this quarter.',
      quote: 'Dream big, but price the reagents.',
    },
    PREPRINT: {
      headline: 'Early-Release Sprinter',
      tagline: 'Put v1 in the world so the world can tell you what v2 needs.',
      traits: ['Drafts may meet daylight', 'Revises before reviewers arrive', 'final_v7 is a phase'],
      warning: 'Can use public feedback as project management.',
      advice: 'Before v1, confirm controls, author order and source data exist.',
      quote: 'Release early, but do not pretend it is perfect.',
    },
    SOLO: {
      headline: 'Independent Research Hermit',
      tagline: 'Give you a door and quiet hours; the hard problem comes apart.',
      traits: ['Solo time switches you on', 'Does not love live reporting', 'Deep work is not a slogan'],
      warning: 'Can be excellent so quietly nobody knows it is happening.',
      advice: 'Keep one small weekly sync: not dazzling, just visible.',
      quote: 'I am not gone. I am calculating.',
    },
    CONTROL: {
      headline: 'Control Condition Guardian',
      tagline: 'Your first question is not how pretty the result is, but compared to what.',
      traits: ['Baseline reflex strong', 'Confound radar active', 'Blank wells have names'],
      warning: 'Can design an exploratory experiment like a moon landing.',
      advice: 'Guard controls that change interpretation; release the ones adding weight.',
      quote: 'Significance without baseline makes me nervous.',
    },
    PIPELINE: {
      headline: 'Workflow Tamer',
      tagline: 'If the same task happens manually a third time, you start scripting.',
      traits: ['Folders queue themselves', 'Parameters are not folklore', 'Logs beat memory'],
      warning: 'Can raise a one-off task into a tool project.',
      advice: 'Confirm the flow will run three more times before building a dashboard.',
      quote: 'Twice is repetition; the third time wants automation.',
    },
    PI: {
      headline: 'Supervisor Mode Loading',
      tagline: 'You say “just checking,” but your calendar is becoming a small lab.',
      traits: ['Sees the whole board', 'Asks about manuscript progress', 'Carries other projects mentally'],
      warning: 'Can drift from data while approaching everyone’s deadlines.',
      advice: 'Keep one small project where your hands still touch data or samples.',
      quote: 'Just a reminder. No pressure.',
    },
    GHOST: {
      headline: 'Meeting Invisibility Specialist',
      tagline: 'Your microphone is quiet; the document suddenly has the answer.',
      traits: ['Camera boundaries clear', 'After-meeting text is excellent', 'Short meetings improve cognition'],
      warning: 'Can filter necessary discussion as ambient noise.',
      advice: 'For the ten minutes where decisions happen, appear once.',
      quote: 'I am here, just not on mic.',
    },
    POLISH: {
      headline: 'Presentation-First Perfectionist',
      tagline: 'The figure has not proven the claim yet, but you know its font.',
      traits: ['Figure legends breathe', 'Colour palettes rescue rooms', 'Sighs before bad layout'],
      warning: 'Can make a pretty figure earn trust before the data have.',
      advice: 'First check what is true; then dress it beautifully.',
      quote: 'Ugly can be fixed. Untrue cannot.',
    },
  },
};

export function getShareCopy(lang: LanguageCode, code: string): ShareCopy {
  return SHARE_COPY[lang]?.[code] ?? SHARE_COPY.en[code] ?? SHARE_COPY.en.BAYES;
}
